
name: vpn_basic_project
description: Flutter Android VPN based on OpenVPN Library.
publish_to: 'none'

# App Version
version: 1.0.2+2

environment:
  sdk: ">=3.4.3 <4.0.0"

# App dependencies
dependencies:
  flutter:
    sdk: flutter

  #getx package for state management
  get: ^4.6.6  
  
  # Cupertino style icons
  cupertino_icons: ^1.0.8

  #for api calls
  http: ^1.2.2

  #converting csv to list
  csv: ^6.0.0

  #lottie animations
  lottie: ^3.1.3

  #storing data in local storage
  hive: ^2.2.3
  hive_flutter: ^1.1.0


dev_dependencies:
  flutter_test:
    sdk: flutter

  # Change package name  
  change_app_package_name: ^1.3.0
  

  # Encourages good practices
  flutter_lints: ^4.0.0

flutter:
  # Enabling material design
  uses-material-design: true

  # App assets
  assets:
    - assets/
    - assets/vpn/
    - assets/images/
    - assets/lottie/
    - assets/flags/